spring.application.name: "tutti-frutti-zeebe-worker"
spring.cloud.config.import-check.enabled: false
server.port: 8090

camunda:
  client:
    mode: self-managed
    enabled: true
    grpc-address: http://127.0.0.1:26500
    rest-address: http://localhost:8080

camunda.client.zeebe.request-timeout: PT10S
camunda.client.zeebe.job-backoff-time: PT30S

logging:
  level:
    com:
      example:
        zeebe_spring_boot_app: DEBUG
    io:
      camunda:
        zeebe: INFO
        client:
          impl:
            CamundaCallCredentials: ERROR
      grpc: WARN
      micrometer: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%15.15thread] %-40.40logger{39} : %msg%n"

logging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials: OFF

services:
  beers:
    url: https://api.sampleapis.com
    ale: "/beers/ale"
    stouts: "/beers/stouts"