spring.application.name: "tutti-frutti-zeebe-worker"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

services:
  beers:
    url: "https://api.sampleapis.com"
    ale: "/beers/ale"
    stouts: "/beers/stouts"